name: Firmware nightly workflow (ESP32)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/firmware_esp32_nightly.yml'
      - 'grid_esp/**'
      - 'grid_common/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files
        run: |
          ls

      - name: Install RP2040 SDK and build co-processor firmware
        run: |
          sudo apt update
          sudo apt install -y git python3 cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
          git clone https://github.com/raspberrypi/pico-sdk.git --branch master
          cd pico-sdk/
          git submodule update --init
          cd ..
          export PICO_SDK_PATH=$(pwd)/pico-sdk/
          echo "The Path: $PICO_SDK_PATH"
          cd grid_pico/
          mkdir -p build
          cd build
          cmake ..
          make
          ls
          ../../grid_esp/pico_header.sh
          cd ../../grid_esp
          cat ./main/pico_firmware.h

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32s3
          path: 'grid_esp'
          command: idf.py --version && idf.py build

      - name: Convert to UF2
        run: |
          cd ./grid_esp
          mkdir ./output
          python3 ./tools/uf2conv.py -f ESP32S3 ./build/grid_fw.bin -b 0x0 -c -o ./output/grid_fw.uf2

      - name: Set Date
        run: echo "action_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Copy and rename the artifact
        run: |
          ls
          cp grid_esp/output/grid_fw.uf2 grid_esp32_nightly_${{ env.action_date }}.uf2

      - uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "Heyo, the ESP32 Nightly Firmware is build ready!"
          filename: "grid_esp32_nightly_${{ env.action_date }}.uf2"

      - uses: actions/upload-artifact@v3
        with:
          name: ESP32 Nightly
          path: grid_esp32_nightly_${{ env.action_date }}.uf2