name: Firmware nightly workflow (ESP32)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/firmware_esp32_nightly.yml'
      - 'grid_esp/**'
      - 'grid_common/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: List files
      - run: |
          ls

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32s3
          path: 'grid_esp'
          command: idf.py build

      - name: Test toolchain
        run: |
          idf.py --version