name: Fuzz Testing

on:
  push:

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64


    - name: Build and run fuzz test
      run: |
        ./fuzz.sh

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Fuzzing Binary
        path: |
          fuzzer_test
          input.bin
