name: Push components to https://components.espressif.com
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'grid_common/**'
      - '.github/workflows/grid_common_package.yml'
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Upload components to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: "grid_common"
          namespace: "sukuwc"
          name: "grid_common"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}